UI toolkit extensions/list view register and scroll functions
onchainstudios/onchainstudios-unity-extensions pull request #37
Opened 2024-04-18 16:33 UTC by njaramillo-onchain

2024-04-18 16:43 UTC, Arthur-OnChainStudios reviewed
Add base class EventBusBridgeBase.cs for both event bus bridges per conversation.

2024-04-18 16:44 UTC, Arthur-OnChainStudios requested changes
See previous comment

2024-04-18 22:11 UTC, rie-kumar-onchain approved these changes

2024-04-23 22:01 UTC, Arthur-OnChainStudios approved these changes

2024-04-23 22:01 UTC, merged